### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by osdaeg** [dendianugerah/velld#24]
Hi. I'm trying to install velld using Docker Compose. The software starts, but I can't get past the login.

The error in question is login error, if I try to start with the credentials I defined in the .env file, and if I want to register I can't

My .env file:

```
NEXT_PUBLIC_API_URL=http://localhost:7655
JWT_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
ADMIN_USERNAME_CREDENTIAL=daniel
ADMIN_PASSWORD_CREDENTIAL=mipassword
ALLOW_REGISTER=true
``` 

My docker-compose.yml:

```dockerfile
api:
    image: ghcr.io/dendianugerah/velld/api:latest
    container_name: velld-api
    ports:
      - "7655:8080"
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires  
    volumes:
      - /home/daniel/docker/dbutils/velld/app/internal/database:/app/internal/database
      - /home/daniel/docker/dbutils/velld/app/backups:/app/backups
    restart: unless-stopped
    networks:
      - BackendNetwork

  web:
    container_name: velld
    image: ghcr.io/dendianugerah/velld/web:latest
    ports:
      - "7656:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      ALLOW_REGISTER: ${ALLOW_REGISTER}
      PUID: 1000
      PGID=: 1000
      TZ=: America/Argentina/Buenos_Aires
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - BackendNetwork
      - GeneralNetwork
``` 

Velld-api logs:

```
2025/10/05 16:15:20 [WARN] No .env file found, will generate secrets if missing
2025/10/05 16:15:20 goose: no migrations to run. current version: 0
2025/10/05 16:15:20 invalid hex-encoded key
2025/10/05 16:15:23 goose: no migrations to run. current version: 0
2025/10/05 16:15:23 invalid hex-encoded key
2025/10/05 16:15:24 goose: no migrations to run. current version: 0
2025/10/05 16:15:24 invalid hex-encoded key
2025/10/05 16:15:26 goose: no migrations to run. current version: 0
2025/10/05 16:15:26 invalid hex-encoded key
2025/10/05 16:15:28 goose: no migrations to run. current version: 0
2025/10/05 16:15:28 invalid hex-encoded key
2025/10/05 16:15:30 goose: no migrations to run. current version: 0
2025/10/05 16:15:30 invalid hex-encoded key
2025/10/05 16:15:34 goose: no migrations to run. current version: 0
2025/10/05 16:15:34 invalid hex-encoded key
2025/10/05 16:15:40 goose: no migrations to run. current version: 0
2025/10/05 16:15:40 invalid hex-encoded key
``` 

Can you help me? Thank you very much!

**Comment by dendianugerah** [comment]
Hey, thanks for pointing that out!

The **ENCRYPTION_KEY** needs to be a 64-character hex string (i.e. 32 random bytes). In your .env, you're using $(openssl rand -hex 32), but .env files don't execute shell commands — so it's being read as a literal string, which causes the invalid hex-encoded key error.

To fix it, just run this in your terminal:

openssl rand -hex 32

Then paste the output directly into your .env like:
ENCRYPTION_KEY=your_generated_key_here

I'll improve the code later so it can handle raw text or give a clearer error. Appreciate the feedback!

**Comment by yewkay** [comment]
I just deployed velld and also can't get past login "Failed to login". i have user and password defined in .env when i try to create a new user via UI it doesn't work as well with "Failed to register"

**Comment by osdaeg** [comment]
I updated Velld because it seemed to have fixed the problem, but it's still
the same. I'm tired of this. I liked an all-in-one solution for my
databases, but I don't know what else to do.

**Comment by yewkay** [comment]
> I updated Velld because it seemed to have fixed the problem, but it's still
> the same. I'm tired of this. I liked an all-in-one solution for my
> databases, but I don't know what else to do.

You could go for paid options like Acronis, they have live database backup solutions. They have reasonable rates that go with a base fee followed by data volume used.

**Comment by TheLion** [comment]
Unfortunately, the issue does still exist after re-deploying the docker containers from scratch.

I did notice that the warning `No .env file found, will generate secrets if missing` does not appear in the log file anymore. So that seems to be solved.

**Comment by dendianugerah** [comment]
> hey there I pulled the latest changes an drestartet velld. unfortunately same erro: can't login. in the browser console I get the hint to look at https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS/Errors/CORSDidNotSucceed maybe that helps?
> 
> with this error in german: Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:8080/api/auth/login. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null). translated: Cross-origin request blocked: The same-source rule prohibits reading the external resource at http://localhost:8080/api/auth/login. (Reason: CORS request failed). Status code: (null).
> 
> Greets

Can you share the output of these commands?

docker compose ps
docker compose logs api | tail -20

**Comment by virse** [comment]
not until now. I really would like to use velld for backing up my databases. It would be a great combination/solution with duplicati. duplicati for the the files and configs and velld for the databases.
